---

- name: ({{ task_filename }}) get UID
  command: "id -u {{ app_user }}"
  changed_when: False
  register: app_uid

- name: ({{ task_filename }}) get GID
  command: "id -g {{ app_user }}"
  changed_when: False
  register: app_gid

- name: "({{ task_filename }}) build {{ app_imagename }} docker image"
  docker_image:
    name: "{{ app_imagename }}:{{ app_version }}"
    build:
      path: "{{ app_build_path }}"
      args: "{{ app_build_args | combine({ 'app_uid': app_uid.stdout, 'app_gid': app_gid.stdout }) }}"
    force_source: yes
    source: build